export const DubaiImages ={
    d1 : require('./portdubai1.jpg').default,
    d2 : require('./portdubai2.jpg').default,
    db1 : require('./dbeach1.jpg').default,
    db2 : require('./dbeach2.jpg').default,
    dc1 : require('./dculture1.jpg').default,
    dc2 : require('./dculture2.jpg').default,
    dh1 : require('./aisha8.jpg.webp').default,
    dh2 : require('./aisha7.jpg').default,
    dp1 : require('./aisha6.jpeg').default,
    dp2 : require('./aisha5.png').default,
    dp3 : require('./aisha4.jpeg').default,
    dp4 : require('./aisha3.jpeg').default, 
    do1 : require('./aisha2.jpg.webp').default,
    do2 : require('./aisha1.png').default,
}